# This playbook install the Collectd Graph Panel (CGP) (https://github.com/pommi/CGP)
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install mosquitto package
  yum: pkg=$item
       state=present 
  with_items:
    - dejavu-fonts-common
    - dejavu-lgc-sans-mono-fonts
    - dejavu-sans-mono-fonts

- name: checkout from the git repo
  git: repo=git://github.com/pommi/CGP.git
       dest=/var/www/lighttpd/cgp

- name: add a new entry to the index.html page
  lineinfile: dest=/var/www/lighttpd/index.html
              regexp='^<!--IN-->'
              insertafter='        <!--IN-->'
              line='        <a href="/cgp" class="btn btn-primary">CGP</a>'
