# This playbook remove all components which were needed for the setup. 
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: remove the unzip package
  command: /usr/bin/dnf -y erase unzip

- name: remove the tar package
  command: /usr/bin/dnf -y erase tar

- name: remove git
  command: /usr/bin/dnf -y erase git
