# This playbook install the Damn Vulnerable Web Application (DVWA) 
# (http://www.dvwa.co.uk/).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: downloads the archive
  get_url: url=http://dvwa.googlecode.com/files/DVWA-$dvwa_version.zip
           dest=/var/www/lighttpd/dvwa-$dvwa_version.zip
           mode=0440

- name: unpack the archive
  command: /usr/bin/unzip -o /var/www/lighttpd/dvwa-$dvwa_version.zip -d /var/www/lighttpd/

- name: delete the archive
  file: path=/var/www/lighttpd/dvwa-$dvwa_version.zip
        state=absent

- name: set the permissions
  file: path=/var/www/lighttpd
        mode=0777
        state=directory

- name: install a default configuration file
  template: src=files/dvwa.j2
            dest=/var/www/lighttpd/dvwa/config/config.inc.php
            owner=root
            group=root
            mode=0755
            backup=yes

- name: add a new entry to the index.html page
  lineinfile: dest=/var/www/lighttpd/index.html
              regexp='^<!--VA-->'
              insertafter='        <!--VA-->'
              line='        <a href="/dvwa" class="btn btn-primary">DVWA</a>'

- name: restart lighttpd
  service: name=lighttpd state=restarted
