# This playbook install the linfo (http://linfo.sourceforge.net/) php
# application.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: download the source tarball
  get_url: url=http://sourceforge.net/projects/linfo/files/Linfo%20Stable%20Releases/linfo-$linfo_version.tar.gz
           dest=/var/www/lighttpd/linfo-$linfo_version.tar.gz
           mode=0440

- name: unpack the source tarball
  command: /usr/bin/tar -xzf /var/www/lighttpd/linfo-$linfo_version.tar.gz -C /var/www/lighttpd/

- name: rename the source directory
  command: /usr/bin/mv /var/www/lighttpd/linfo-$linfo_version /var/www/lighttpd/linfo

- name: delete the archive
  file: path=/var/www/lighttpd/linfo-$linfo_version.tar.gz
        state=absent

- name: copy the default config file
  command: /usr/bin/cp /var/www/lighttpd/linfo/sample.config.inc.php /var/www/lighttpd/linfo/config.inc.php

- name: add a new entry to the index.html page
  lineinfile: dest=/var/www/lighttpd/index.html
              regexp='^<!--IN-->'
              insertafter='        <!--IN-->'
              line='        <a href="/linfo" class="btn btn-primary">linfo</a>'
