# This playbook install the mosquitto broker (http://mosquitto.org).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install mosquitto package
  yum: pkg=$item
       state=present 
  with_items:
    - mosquitto

- name: configure firewall, allow traffic on port 1883
  command: /usr/bin/firewall-cmd --permanent --add-port=1883/tcp

- name: reload firewall configuration
  command: /usr/bin/firewall-cmd --reload

- name: start mosquitto
  service: name=mosquitto
           state=running
           enabled=yes
