# This playbook setup nfs (http://nfs.sourceforge.net/) capability.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install nfs package
  yum: pkg={{ item }}
       state=present 
  with_items:
    - nfs-utils

- name: create a directory to share
  file: path=/opt/nfs/
        mode=0755
        state=directory

- name: put a dummy in the share
  template: src=files/default.j2
            dest=/opt/nfs/info.txt
            mode=0644

- name: add an export
  lineinfile: dest=/etc/exports
              regexp=''
              insertafter=EOF
              line='/opt/nfs/ {{ansible_eth0.ipv4.network }}/24(rw,sync)'

- name: configure firewall, allow traffic to port 1883
  firewalld: aervice=nfs
             permanent=true
             state=enabled

#- name: start rpcbind
#  service: name=rpcbind
#           state=running
#           enabled=yes

#- name: start nfs-server
#  service: name=nfs-server
#           state=running
#           enabled=yes

#- name: start nfs-idmap
#  service: name=nfs-idmap
#           state=running
#           enabled=yes

#- name: start nfs-lock
#  service: name=nfs-lock
#           state=running
#           enabled=yes
