# This playbook install phpmyadmin (http://www.phpmyadmin.net).
#
# Copyright (c) 2013-2020 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install additional php packages
  dnf:
    pkg: "{{ item }}"
    state: present
  with_items:
    - php-mysql
    - php-mcrypt
    - php-mbstring
    - php-gd

- name: download the source tarball
  get_url:
    url: http://files.directadmin.com/services/all/phpMyAdmin/phpMyAdmin-{{ phpmyadmin_version }}-all-languages.tar.gz
    dest: /var/www/lighttpd/phpmyadmin-{{ phpmyadmin_version }}.tar.gz
    mode: 0440

- name: unpack the source tarball
  command: /usr/bin/tar -xzf /var/www/lighttpd/phpmyadmin-{{ phpmyadmin_version }}.tar.gz -C /var/www/lighttpd/

- name: rename the source directory
  command: /usr/bin/mv /var/www/lighttpd/phpMyAdmin-{{ phpmyadmin_version }}-all-languages /var/www/lighttpd/phpmyadmin

- name: delete the archive
  file:
    path: /var/www/lighttpd/phpmyadmin-{{ phpmyadmin_version }}.tar.gz
    state: absent
