# This playbook install phpshell (http://phpshell.sourceforge.net/).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install archiver tool
  command: /usr/bin/dnf -y install tar

- name: download the source tarball
  get_url: url=http://prdownloads.sourceforge.net/phpshell/phpshell-$phpshell_version.tar.gz
           dest=/var/www/lighttpd/phpshell-$phpshell_version.tar.gz
           mode=0440

- name: unpack the source tarball
  command: /usr/bin/tar -xzf /var/www/lighttpd/phpshell-$phpshell_version.tar.gz -C /var/www/lighttpd/

- name: rename the source directory
  command: /usr/bin/mv /var/www/lighttpd/phpshell-$phpshell_version /var/www/lighttpd/phpshell

- name: delete the archive
  file: path=/var/www/lighttpd/phpshell-$phpshell_version.tar.gz
        state=absent

- name: set the permissions
  file: path=/usr/share/webapps/
        mode=0777
        state=directory

- name: add a new entry to the index.html page
  lineinfile: dest=/var/www/lighttpd/index.html
              regexp='^<!--SH-->'
              insertafter='        <!--SH-->'
              line='        <a href="/phpshell/phpshell.php" class="btn btn-primary">PHPShell</a>'

- name: remove archiver tool
  command: /usr/bin/dnf -y erase tar
