# This playbook install the SQLI Labs (https://github.com/Audi-1/sqli-labs).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: delete a previous checkout
  file: path=/var/www/lighttpd/sqli-labs
        state=absent

- name: checkout from the git repo
  git: repo=git://github.com/Audi-1/sqli-labs.git
       dest=/var/www/lighttpd/sqli-labs

- name: set the right permission
  file: path=/var/www/lighttpd/
        mode=0777
        state=directory

- name: install a default configuration file
  template: src=files/sqli.j2
            dest=/var/www/lighttpd/sqli-labs/sql-connections/db-creds.inc
            owner=root
            group=root
            mode=0755
            backup=yes

- name: add a new entry to the index.html page
  lineinfile: dest=/var/www/lighttpd/index.html
              regexp='^<!--VA-->'
              insertafter='        <!--VA-->'
              line='        <a href="/sqli-labs" class="btn btn-primary">SQLI Labs</a>'
