# This playbook install the wso shell (https://github.com/orbweb/PHP-SHELL-WSO).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: create the directory
  file: path=/var/www/lighttpd/wso
        state=directory

- name: download the source
  get_url: url=https://github.com/downloads/orbweb/PHP-SHELL-WSO/wso2.5.1.php
           dest=/var/www/lighttpd/wso/wso.php
           mode=0777

- name: set the right permission
  file: path=/var/www/lighttpd/
        mode=0777
        state=directory

- name: add a new entry to the index.html page
  lineinfile: dest=/var/www/lighttpd/index.html
              regexp='^<!--SH-->'
              insertafter='        <!--SH-->'
              line='        <a href="/wso/wso.php" class="btn btn-primary">WSO</a>'
