# This variables file contains the version numbers of the software packages
# which will be installed without the package management tool and basic release
# number as helper variables for playbooks.
#
# Copyright (c) 2013-2019 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
### Operating systems
# Fedora - http://fedoraproject.org
fedora_previous: 28
fedora_current: 29
fedora_next: 30

# Alpine - http://alpinelinux.org/
alpine_current: 3.9.2

# Freedos - http://www.freedos.org
freedos_previous: 1.0
freedos_current: 11

# DBAN - http://www.dban.org
dban_current: 2.3.0

# HDT- http://hdt-project.org
hdt_current: 0.5.2

# xPUD - http://www.xpud.org
xpud_current: 0.9.2

### Application
# linfo - http://linfo.sourceforge.net
linfo_version: 2.0.3

# piwik - http://piwik.org/
piwik_version: 2.16.1

# phpsysinfo - https://github.com/phpsysinfo/phpsysinfo
phpsysinfo_version: 3.3.0

# phpshell - http://phpshell.sourceforge.net
phpshell_version: 2.4

# phpMyAdmin- http://www.phpmyadmin.net
phpmyadmin_version: 4.8.4

# DokuWiki - https://www.dokuwiki.org/dokuwiki
dokuwiki_version: 2015-08-10a

# Bootstrap - http://getbootstrap.com
bootstrap_version: 4.1.3

