# This variables file contains the version numbers of the software packages
# which will be installed without the package management tool and basic release
# number as helper variables for playbooks.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
### Operating systems
# Fedora - http://fedoraproject.org
fedora_previous: 19
fedora_current: 20
fedora_next: 21

# Alpine - http://alpinelinux.org/
alpine_current: 2.7.3

# Freedos - http://www.freedos.org
freedos_previous: 1.0
freedos_current: 11

# DBAN - http://www.dban.org
dban_current: 2.2.8

# HDT- http://hdt-project.org
hdt_current: 0.5.2

# xPUD - http://www.xpud.org
xpud_current: 0.9.2

### Application
# linfo - http://linfo.sourceforge.net
linfo_version: 1.9

# piwik - http://piwik.org/
piwik_version: 2.2.0

# phpsysinfo - http://rk4an.github.com/phpsysinfo
phpsysinfo_version: 3.1.11

# phpshell - http://phpshell.sourceforge.net
phpshell_version: 2.4

# phpMyAdmin- http://www.phpmyadmin.net
phpmyadmin_version: 4.1.14

# DokuWiki - https://www.dokuwiki.org/dokuwiki
dokuwiki_version: 2013-03-06

# Bootstrap - http://getbootstrap.com
bootstrap_version: 3.1.1
