# This playbook contains the tasks for the 'common' role.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: distribute motd file
  template: src=motd.j2
            dest=/etc/motd
            owner=root
            group=root
            mode=0644
